services:
  - type: web
    name: customer-churn-prediction
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.wsgi:app
    envVars:
      - key: PORT
        value: 10000
