services:
  - type: web
    name: customer-churn-predictor
    runtime: python
    buildCommand: ""
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PORT
        value: 10000
    plan: free
